# Generated by Django 5.2.8 on 2025-11-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0006_groundhandler_airline_ground_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Flight number (e.g., 920)', max_length=10)),
                ('date_of_operation', models.DateField(help_text='Date of flight operation')),
                ('flight_id', models.CharField(help_text='Unique flight identifier (e.g., YYYYMMDD-XX123)', max_length=20, unique=True)),
                ('registration', models.CharField(blank=True, help_text='Aircraft registration (tail number)', max_length=10)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('OFB', 'Off Block'), ('AIR', 'Airborne'), ('LND', 'Landed'), ('ONB', 'On Block'), ('FIB', 'First Bag'), ('LSB', 'Last Bag'), ('CXX', 'Cancelled'), ('DIV', 'Diverted')], default='SCH', max_length=3)),
                ('stod', models.DateTimeField(help_text='Scheduled Time of Departure')),
                ('etod', models.DateTimeField(blank=True, help_text='Estimated Time of Departure', null=True)),
                ('aobt', models.DateTimeField(blank=True, help_text='Actual Off-Block Time', null=True)),
                ('atod', models.DateTimeField(blank=True, help_text='Actual Time of Departure (Wheels Up)', null=True)),
                ('stoa', models.DateTimeField(help_text='Scheduled Time of Arrival')),
                ('etoa', models.DateTimeField(blank=True, help_text='Estimated Time of Arrival', null=True)),
                ('atoa', models.DateTimeField(blank=True, help_text='Actual Time of Arrival (Touchdown)', null=True)),
                ('aibt', models.DateTimeField(blank=True, help_text='Actual In-Block Time', null=True)),
                ('public_remark', models.CharField(blank=True, help_text="Public display message (e.g., 'Go to Gate')", max_length=50)),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data for mobile boarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.aircrafttype')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.airline')),
                ('carousel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.baggagecarousel')),
                ('checkin_counters', models.ManyToManyField(blank=True, to='masterdata.checkincounter')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_arrivals', to='masterdata.airport')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.gate')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_departures', to='masterdata.airport')),
            ],
            options={
                'verbose_name': 'Daily Flight',
                'verbose_name_plural': 'Daily Flights',
                'ordering': ['date_of_operation', 'stod', 'airline', 'flight_number'],
            },
        ),
    ]
