# Generated by Django 5.2.8 on 2025-11-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_ops', '0001_initial'),
        ('masterdata', '0006_groundhandler_airline_ground_handler'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyflight',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Source seasonal flight (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.seasonalflight'),
        ),
        migrations.AddField(
            model_name='dailyflight',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.stand'),
        ),
        migrations.AddIndex(
            model_name='dailyflight',
            index=models.Index(fields=['date_of_operation', 'airline'], name='flight_ops__date_of_0a19c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyflight',
            index=models.Index(fields=['status'], name='flight_ops__status_7a8ef6_idx'),
        ),
    ]
