# Generated by Django 5.2.8 on 2025-11-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_ops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyflight',
            name='is_manually_modified',
            field=models.BooleanField(default=False, help_text='True if this flight has been manually edited (prevents auto-propagation)'),
        ),
        migrations.AddField(
            model_name='dailyflight',
            name='last_propagated_at',
            field=models.DateTimeField(blank=True, help_text='Last time this flight was updated from seasonal schedule', null=True),
        ),
        migrations.AddField(
            model_name='dailyflight',
            name='schedule_version',
            field=models.IntegerField(default=1, help_text='Version of the seasonal schedule used to generate this flight'),
        ),
    ]
