# Generated by Django 5.2.8 on 2025-11-22 03:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(help_text='ICAO aircraft type code (e.g., A320, B77W)', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{3,4}$')])),
                ('iata_code', models.CharField(blank=True, help_text='IATA aircraft type code (e.g., 320, 777)', max_length=3, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('wake_turbulence', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy'), ('J', 'Super (A380)')], default='M', max_length=1)),
                ('size_category', models.CharField(choices=[('NB', 'Narrow Body'), ('WB', 'Wide Body'), ('RJ', 'Regional Jet')], default='NB', max_length=2)),
                ('wingspan_meters', models.DecimalField(decimal_places=2, help_text='Wingspan in meters', max_digits=5)),
                ('length_meters', models.DecimalField(decimal_places=2, help_text='Aircraft length in meters', max_digits=5)),
                ('max_takeoff_weight_kg', models.IntegerField(help_text='MTOW in kilograms')),
                ('typical_capacity', models.IntegerField(help_text='Typical passenger capacity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'ordering': ['icao_code'],
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(help_text='2-letter IATA code (e.g., TG, SQ)', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2}$')])),
                ('icao_code', models.CharField(help_text='3-letter ICAO code (e.g., THA, SIA)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stand code (e.g., R1, R2, A10)', max_length=10, unique=True)),
                ('size_code', models.CharField(choices=[('A', 'Code A (Wingspan < 15m)'), ('B', 'Code B (Wingspan 15-24m)'), ('C', 'Code C (Wingspan 24-36m)'), ('D', 'Code D (Wingspan 36-52m)'), ('E', 'Code E (Wingspan 52-65m)'), ('F', 'Code F (Wingspan 65-80m)')], default='C', max_length=1)),
                ('max_wingspan_meters', models.DecimalField(decimal_places=2, help_text='Maximum wingspan', max_digits=5)),
                ('has_pushback', models.BooleanField(default=True, help_text='Requires pushback (not self-maneuver)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stands',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Terminal code (e.g., T1, T2, Domestic)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Gate code (e.g., A1, B12, C3)', max_length=10, unique=True)),
                ('gate_type', models.CharField(choices=[('CONTACT', 'Contact Stand (Jetbridge)'), ('REMOTE', 'Remote Stand (Bus)'), ('BOTH', 'Flexible (Both)')], default='CONTACT', max_length=10)),
                ('max_wingspan_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum wingspan restriction', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for allocation')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_aircraft_types', models.ManyToManyField(blank=True, help_text='Restrict gate to specific aircraft types (leave empty for all)', to='masterdata.aircrafttype')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='masterdata.terminal')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CheckInCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Counter code (e.g., A1, A2, B10-B15)', max_length=10, unique=True)),
                ('counter_group', models.CharField(blank=True, help_text="Group name (e.g., 'Row A', 'Island 1')", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_counters', to='masterdata.terminal')),
            ],
            options={
                'verbose_name': 'Check-in Counter',
                'verbose_name_plural': 'Check-in Counters',
                'ordering': ['terminal', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BaggageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Carousel code (e.g., C1, C2)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_carousels', to='masterdata.terminal')),
            ],
            options={
                'verbose_name': 'Baggage Carousel',
                'verbose_name_plural': 'Baggage Carousels',
                'ordering': ['terminal', 'code'],
            },
        ),
    ]
