# Generated by Django 5.2.8 on 2025-11-29 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(help_text='3-letter IATA code (e.g., LHR, DXB)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('icao_code', models.CharField(help_text='4-letter ICAO code (e.g., EGLL, OMDB)', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}$')])),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['iata_code'],
            },
        ),
    ]
