# Generated by Django 5.2.8 on 2025-11-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designator (e.g., 09L/27R)', max_length=10)),
                ('length_meters', models.IntegerField(help_text='Total length in meters')),
                ('width_meters', models.IntegerField(help_text='Width in meters')),
                ('surface', models.CharField(choices=[('CONCRETE', 'Concrete'), ('ASPHALT', 'Asphalt'), ('GRASS', 'Grass')], default='CONCRETE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Runway',
                'verbose_name_plural': 'Runways',
            },
        ),
    ]
