# Generated by Django 5.2.8 on 2025-11-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_runway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeshare', models.BooleanField(default=False)),
                ('stops', models.IntegerField(default=0)),
                ('equipment', models.CharField(blank=True, help_text='Aircraft types (e.g., 320 777)', max_length=100, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='masterdata.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='masterdata.airport')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'unique_together': {('airline', 'origin', 'destination')},
            },
        ),
    ]
