# Generated by Django 5.2.8 on 2025-11-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_route_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code (e.g., BFS, TGGS)', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('provides_passenger', models.BooleanField(default=True, help_text='Check-in, Gate, Boarding')),
                ('provides_ramp', models.BooleanField(default=True, help_text='Baggage, Pushback, Cleaning')),
                ('provides_cargo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ground Handler',
                'verbose_name_plural': 'Ground Handlers',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='ground_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airlines', to='masterdata.groundhandler'),
        ),
    ]
