# Generated by Django 5.2.8 on 2025-12-06 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_groundhandler_airline_ground_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='stand',
            field=models.ForeignKey(blank=True, help_text='Physical stand/parking position for this gate', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate', to='masterdata.stand'),
        ),
    ]
