# Generated by Django 5.2.8 on 2025-11-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0006_groundhandler_airline_ground_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Flight number (e.g., 920)', max_length=10)),
                ('service_type', models.CharField(default='J', help_text='J=Scheduled Passenger, F=Cargo', max_length=1)),
                ('stod', models.TimeField(help_text='Scheduled Time of Departure (UTC)')),
                ('stoa', models.TimeField(help_text='Scheduled Time of Arrival (UTC)')),
                ('start_date', models.DateField(help_text='Season start date')),
                ('end_date', models.DateField(help_text='Season end date')),
                ('days_of_operation', models.CharField(help_text='Days: 1=Mon, 2=Tue... 7=Sun (e.g., 1357 for Mon/Wed/Fri/Sun)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.aircrafttype')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_schedules', to='masterdata.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_schedules', to='masterdata.airport')),
            ],
            options={
                'verbose_name': 'Seasonal Flight',
                'verbose_name_plural': 'Seasonal Flights',
                'ordering': ['airline', 'flight_number', 'start_date'],
                'unique_together': {('airline', 'flight_number', 'start_date')},
            },
        ),
    ]
