# Generated by Django 5.2.8 on 2025-12-06 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_groundhandler_airline_ground_handler'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalflight',
            name='preferred_carousel',
            field=models.ForeignKey(blank=True, help_text='Default baggage claim carousel for arrivals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_flights', to='masterdata.baggagecarousel'),
        ),
        migrations.AddField(
            model_name='seasonalflight',
            name='preferred_gate',
            field=models.ForeignKey(blank=True, help_text='The standard gate negotiated for this flight series (validated against aircraft compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_flights', to='masterdata.gate'),
        ),
        migrations.AddField(
            model_name='seasonalflight',
            name='preferred_stand',
            field=models.ForeignKey(blank=True, help_text='Parking position if gate is not available or for cargo/long layovers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_flights', to='masterdata.stand'),
        ),
    ]
